/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowTintRouteImport } from './routes/window-tint'
import { Route as VipShowroomRouteImport } from './routes/vip-showroom'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PaintProtectionRouteImport } from './routes/paint-protection'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DetailingRouteImport } from './routes/detailing'
import { Route as CeramicCoatingRouteImport } from './routes/ceramic-coating'
import { Route as CarWrapsRouteImport } from './routes/car-wraps'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendBookingEmailRouteImport } from './routes/api/public/send-booking-email'

const WindowTintRoute = WindowTintRouteImport.update({
  id: '/window-tint',
  path: '/window-tint',
  getParentRoute: () => rootRouteImport,
} as any)
const VipShowroomRoute = VipShowroomRouteImport.update({
  id: '/vip-showroom',
  path: '/vip-showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintProtectionRoute = PaintProtectionRouteImport.update({
  id: '/paint-protection',
  path: '/paint-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailingRoute = DetailingRouteImport.update({
  id: '/detailing',
  path: '/detailing',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicCoatingRoute = CeramicCoatingRouteImport.update({
  id: '/ceramic-coating',
  path: '/ceramic-coating',
  getParentRoute: () => rootRouteImport,
} as any)
const CarWrapsRoute = CarWrapsRouteImport.update({
  id: '/car-wraps',
  path: '/car-wraps',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendBookingEmailRoute =
  ApiPublicSendBookingEmailRouteImport.update({
    id: '/api/public/send-booking-email',
    path: '/api/public/send-booking-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/car-wraps': typeof CarWrapsRoute
  '/ceramic-coating': typeof CeramicCoatingRoute
  '/detailing': typeof DetailingRoute
  '/faq': typeof FaqRoute
  '/paint-protection': typeof PaintProtectionRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/vip-showroom': typeof VipShowroomRoute
  '/window-tint': typeof WindowTintRoute
  '/api/public/send-booking-email': typeof ApiPublicSendBookingEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/car-wraps': typeof CarWrapsRoute
  '/ceramic-coating': typeof CeramicCoatingRoute
  '/detailing': typeof DetailingRoute
  '/faq': typeof FaqRoute
  '/paint-protection': typeof PaintProtectionRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/vip-showroom': typeof VipShowroomRoute
  '/window-tint': typeof WindowTintRoute
  '/api/public/send-booking-email': typeof ApiPublicSendBookingEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/car-wraps': typeof CarWrapsRoute
  '/ceramic-coating': typeof CeramicCoatingRoute
  '/detailing': typeof DetailingRoute
  '/faq': typeof FaqRoute
  '/paint-protection': typeof PaintProtectionRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/vip-showroom': typeof VipShowroomRoute
  '/window-tint': typeof WindowTintRoute
  '/api/public/send-booking-email': typeof ApiPublicSendBookingEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/car-wraps'
    | '/ceramic-coating'
    | '/detailing'
    | '/faq'
    | '/paint-protection'
    | '/reviews'
    | '/service-areas'
    | '/vip-showroom'
    | '/window-tint'
    | '/api/public/send-booking-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/car-wraps'
    | '/ceramic-coating'
    | '/detailing'
    | '/faq'
    | '/paint-protection'
    | '/reviews'
    | '/service-areas'
    | '/vip-showroom'
    | '/window-tint'
    | '/api/public/send-booking-email'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/car-wraps'
    | '/ceramic-coating'
    | '/detailing'
    | '/faq'
    | '/paint-protection'
    | '/reviews'
    | '/service-areas'
    | '/vip-showroom'
    | '/window-tint'
    | '/api/public/send-booking-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CarWrapsRoute: typeof CarWrapsRoute
  CeramicCoatingRoute: typeof CeramicCoatingRoute
  DetailingRoute: typeof DetailingRoute
  FaqRoute: typeof FaqRoute
  PaintProtectionRoute: typeof PaintProtectionRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  VipShowroomRoute: typeof VipShowroomRoute
  WindowTintRoute: typeof WindowTintRoute
  ApiPublicSendBookingEmailRoute: typeof ApiPublicSendBookingEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window-tint': {
      id: '/window-tint'
      path: '/window-tint'
      fullPath: '/window-tint'
      preLoaderRoute: typeof WindowTintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-showroom': {
      id: '/vip-showroom'
      path: '/vip-showroom'
      fullPath: '/vip-showroom'
      preLoaderRoute: typeof VipShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paint-protection': {
      id: '/paint-protection'
      path: '/paint-protection'
      fullPath: '/paint-protection'
      preLoaderRoute: typeof PaintProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailing': {
      id: '/detailing'
      path: '/detailing'
      fullPath: '/detailing'
      preLoaderRoute: typeof DetailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramic-coating': {
      id: '/ceramic-coating'
      path: '/ceramic-coating'
      fullPath: '/ceramic-coating'
      preLoaderRoute: typeof CeramicCoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-wraps': {
      id: '/car-wraps'
      path: '/car-wraps'
      fullPath: '/car-wraps'
      preLoaderRoute: typeof CarWrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-booking-email': {
      id: '/api/public/send-booking-email'
      path: '/api/public/send-booking-email'
      fullPath: '/api/public/send-booking-email'
      preLoaderRoute: typeof ApiPublicSendBookingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CarWrapsRoute: CarWrapsRoute,
  CeramicCoatingRoute: CeramicCoatingRoute,
  DetailingRoute: DetailingRoute,
  FaqRoute: FaqRoute,
  PaintProtectionRoute: PaintProtectionRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  VipShowroomRoute: VipShowroomRoute,
  WindowTintRoute: WindowTintRoute,
  ApiPublicSendBookingEmailRoute: ApiPublicSendBookingEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
